version: "3.7"
services:

  restapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: restapi_server
    environment:
      DB_USER: devuser
      DB_PWD: devuser
      DB_NAME: campaignsDB
      DB_HOST: my_mongodb
      DB_PORT: 27017
      CORS_ORIGINS: '*'
    volumes:
      - ./data/applogs:/tmp/logs
    ports:
      - 8080:8080
    depends_on:
      - mongo-database
      
  mongo-database:
    image: mongo
    container_name: mongodb_server
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 
      MONGO_INITDB_DATABASE: campaignsDB
    volumes:
      - ./init-mongo.js/:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017